import { ProjectProps } from "./projects.types";

export const projects: Array<ProjectProps> = [
  {
    key: 0,
    name: "Dumbel - Bumble for Developers",
    isGrid: true,
    url: "https://dumbel.vercel.app/",
    description:
      "Dumbel is like Bumble but for developers, just signin with Github and explore profiles of developers from all over the world! It has 25+ users at present.",
    preview: require("@/public/projects/dumbel.png"),
    skills: ["nextjs", "nestjs", "mongodb", "tailwindcss", "shadcn"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2023,
    filter: "full-stack",
  },
  {
    key: 1,
    name: "CodeChat - Peer Coding Platform",
    isGrid: true,
    url: "https://code-chat-flame.vercel.app/",
    description:
      "A Web based application which allows users to create code rooms and code together, with support of some cool features.",
    preview: require("@/public/projects/codechat.png"),
    skills: ["nextjs", "expressjs", "socketio", "tailwind", "next-auth"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2023,
    filter: "full-stack",
  },
  {
    key: 2,
    name: "Ticket Reselling App",
    url: "https://ticketoo.vercel.app/",
    description:
      "A platform to reshare tickets for events you can't attend, just add your tickets and get buyers rollin.",
    preview: require("@/public/projects/ricket.png"),
    skills: ["nextjs", "expressjs", "mongodb", "css"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2023,
    filter: "full-stack",
  },
  //  {
  //     key:3,
  //     name: "String Reverse",
  //     url: 'https://www.npmjs.com/package/fnpm-package',
  //     description: "",
  //     preview: "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
  //     skills: ["nodejs","javascript"],
  //     extras: "(300+ downloads)",
  //     type:"tech",
  //     madeat: "npm",
  //     year: 2023,
  //     filter:'packages'
  // },

  {
    key: 4,
    name: "Surplus - Manage Expenses",
    isGrid: true,
    url: "https://play.google.com/store/apps/details?id=in.surplusapp&hl=en_IN&gl=US&pli=1",
    description:
      "I worked as Frontend Intern at Surplus. Surplus helps you manage your expenses easily. I built the Bill Payments and Subscription tracking features in the application.",
    preview: require("@/public/surplus.png"),
    skills: ["react-native", "api", "redux", "typescript"],
    extras: "",
    type: "tech",
    madeat: "Surplus",
    year: 2023,
    filter: "mobile-app",
  },
  {
    key: 5,
    name: "Goldenfarms - AgriTech",
    url: "https://play.google.com/store/apps/details?id=com.goldenfarms&hl=en_IE",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["react-native", "api", "redux"],
    extras: "",
    type: "tech",
    madeat: "Simplifii",
    year: 2023,
    filter: "mobile-app",
  },
  {
    key: 6,
    name: "TEDx Website",
    url: "https://tedxabesec.in",
    description: "Website built for TED event in college",
    preview: require("@/public/projects/ricket.png"),
    skills: ["html", "bootstrap", "animation", "css"],
    extras: "",
    type: "tech",
    madeat: "TEDxABESEC",
    year: 2022,
    filter: "miscellaneous",
  },
  {
    key: 7,
    name: "Genero Website",
    url: "https://genero.live",
    description: "Website built for TED event in college",
    preview: require("@/public/projects/ricket.png"),
    skills: ["reactjs", "bootstrap", "animation", "css"],
    extras: "",
    type: "tech",
    madeat: "ABESEC",
    year: 2022,
    filter: "miscellaneous",
  },
  {
    key: 8,
    name: "Portfolio Generator",
    url: "https://github.com/RamGoel/portify",
    description: "Website built for TED event in college",
    preview: require("@/public/projects/ricket.png"),
    skills: ["ejs", "bootstrap", "nodejs", "css"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2022,
    filter: "full-stack",
  },
  {
    key: 9,
    name: "Zomato Interview Experience (Intern+FTE)",
    url: "https://medium.com/@rgoel766/zomato-interview-experience-intern-fte-6d2704ec90aa",
    description: "2023",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*UMz7Mq142riGvYLaNQxg9Q.png",
    skills: [],
    extras: "",
    type: "blog",
    madeat: "Medium",
    year: 2023,
    filter: "blog",
  },
  {
    key: 10,
    name: "Importance of OG tags for link previews",
    url: "https://medium.com/@rgoel766/importance-of-og-title-and-twitter-title-tags-for-link-previews-9c303a667b9e",
    description: "2023",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*UOOR83PW27Wb5-ly23VrGg.jpeg",
    skills: [],
    extras: "",
    type: "blog",
    madeat: "Medium",
    year: 2022,
    filter: "blog",
  },
  {
    key: 11,
    name: "useEffect in React : Complete Guide",
    url: "https://medium.com/@rgoel766/useeffect-hook-in-react-a-comprehensive-guide-2ea0312a5c8",
    description: "2023",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: [],
    extras: "",
    type: "blog",
    madeat: "Medium",
    year: 2022,
    filter: "blog",
  },
  {
    key: 12,
    name: "Sales Dashboard",
    url: "https://dukaan-2024.netlify.app/",
    description: "2024",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["reactjs", "tailwind"],
    extras: "",
    type: "tech",
    madeat: "Dukaan",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 13,
    name: "Link Manager Extension",
    url: "https://addons.mozilla.org/en-US/firefox/addon/linkify/",
    description: "2023",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["html", "service-worker"],
    extras: "",
    type: "tech",
    madeat: "Mozilla",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 14,
    name: "CDN Links Extension",
    url: "https://addons.mozilla.org/en-US/firefox/addon/cdnextension/",
    description: "2022",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["html", "css", "api"],
    extras: "",
    type: "tech",
    madeat: "Mozilla",
    year: 2022,
    filter: "miscellaneous",
  },
  {
    key: 15,
    name: "Ticket reselling bot",
    url: "https://twitter.com/theramgoel/status/1709262222072180879",
    description:
      "A Telegram bot that allows to resell tickets for events which you can't attend. ",
    preview: "https://twitter.com/theramgoel/status/1709262222072180879",
    skills: ["expressjs", "mongodb", "telegram-api"],
    extras: "",
    type: "tech",
    madeat: "Telegram",
    year: 2022,
    filter: "miscellaneous",
  },
  {
    key: 16,
    name: "Web-tools",
    url: "https://github.com/RamGoel/gpt-tools",
    description:
      "A Telegram bot that allows to resell tickets for events which you can't attend. ",
    preview: "https://twitter.com/theramgoel/status/1709262222072180879",
    skills: ["prompt-engineering", "github"],
    extras: "",
    type: "tech",
    madeat: "Github",
    year: 2022,
    filter: "miscellaneous",
  },
  {
    key: 17,
    name: "Hackathon Website",
    url: "https://hackhaven.tech/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["html", "css", "api"],
    extras: "",
    type: "tech",
    madeat: "GDSC",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 18,
    name: "Bakery Checkout",
    url: "https://gan-assesment.netlify.app/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["nextjs", "redux"],
    extras: "",
    type: "tech",
    madeat: "Gan.ai",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 19,
    name: "Paperform UI Clone",
    url: "https://playmo-task.vercel.app/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["nextjs", "tailwindcss", "typescript"],
    extras: "",
    type: "tech",
    madeat: "Playmo",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 20,
    name: "Social Media Feed",
    url: "https://groww-next.vercel.app/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["nextjs", "unsplash-api", "redux"],
    extras: "",
    type: "tech",
    madeat: "Groww",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 21,
    name: "Internship Finding App",
    url: "https://fintern.netlify.app/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["reactjs", "redux"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 22,
    name: "Google Docs Editor Clone",
    url: "https://docsclone1.netlify.app/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["reactjs"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 23,
    name: "Loan Company Website",
    url: "https://loanuncle.com/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["html", "bootstrap"],
    extras: "",
    type: "tech",
    madeat: "Freelance",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 24,
    name: "Ecommerce Listing App",
    url: "https://github.com/RamGoel/ecommerce",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["react-native", "api", "redux"],
    extras: "",
    type: "tech",
    madeat: "Surplus",
    year: 2023,
    filter: "mobile-app",
  },

  {
    key: 25,
    name: "Todo App",
    url: "https://github.com/RamGoel/todo-react-native",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["react-native"],
    extras: "",
    type: "tech",
    madeat: "Freelance",
    year: 2023,
    filter: "mobile-app",
  },
  {
    key: 26,
    name: "Instagram clone",
    url: "https://ig-clone-reactjs.netlify.app/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["reactjs"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 27,
    name: "Malnutrition Fighting App",
    url: "https://feedwell.netlify.app/",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["reactjs"],
    extras: "",
    type: "tech",
    madeat: "Rajasthan Hackathon",
    year: 2023,
    filter: "miscellaneous",
  },
  //   {
  //     key: 28,
  //     name: "Teamo",
  //     url: "https://teamo-next.vercel.app",
  //     description: "",
  //     preview:
  //       "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
  //     skills: ["nextjs", "mongodb", "express", "tailwind"],
  //     extras: "",
  //     type: "tech",
  //     madeat: "Learning",
  //     year: 2023,
  //     filter: "full-stack",
  //   },
  {
    key: 29,
    name: "OTP Auth in React",
    url: "https://github.com/RamGoel/otp-verify-react",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["reactjs"],
    extras: "",
    type: "tech",
    madeat: "Simplifii",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 30,
    name: "String Reverse",
    url: "https://www.npmjs.com/package/fnpm-package",
    description: "",
    preview:
      "https://miro.medium.com/v2/resize:fit:1100/format:webp/1*sqT7dmx7PR4xKnyVJPiYeg.png",
    skills: ["nodejs", "javascript"],
    extras: "(300+ downloads)",
    type: "tech",
    madeat: "npm",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 31,
    name: "Stocks Listing App",
    url: "https://groww-task-delta.vercel.app/",
    description: "",
    preview: "https://groww-task-delta.vercel.app/",
    skills: ["nextjs", "stocks-api", "redux", "typescript"],
    extras: "",
    type: "tech",
    madeat: "Groww",
    year: 2023,
    filter: "miscellaneous",
  },
  {
    key: 32,
    name: "Research Conference app",
    url: "https://orgarch.netlify.app/",
    description: "",
    preview: "https://orgarch.netlify.app/",
    skills: ["reactjs", "firebase", "tailwindcss"],
    extras: "",
    type: "tech",
    madeat: "College",
    year: 2023,
    filter: "full-stack",
  },
  {
    key: 33,
    name: "Calculator App",
    url: "https://www.amazon.in/Sitern-SimpliCalc/dp/B0BR648T88",
    description:
      "Surplus helps you manage your expenses easily. It provides you a unified view of your payment habits and you can even pay bills with surplus.",
    preview: "",
    skills: ["react-native", "typescript"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2023,
    filter: "mobile-app",
  },
  {
    key: 34,
    name: "Lekhak - Anonymous Sharing",
    url: "https://github.com/RamGoel/Lekhak",
    description: "",
    preview: "",
    skills: ["ejs", "expressjs"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2020,
    filter: "miscellaneous",
  },
  {
    key: 35,
    name: "QR based Resume builder",
    url: "https://github.com/RamGoel/QResume",
    description: "",
    preview: "",
    skills: ["html", "css", "js"],
    extras: "",
    type: "tech",
    madeat: "Learning",
    year: 2021,
    filter: "miscellaneous",
  },
  {
    key: 36,
    name: "Mi Store Billing App",
    url: "https://github.com/RamGoel/XiBiller-Stable",
    description: "",
    preview: "",
    skills: ["react-native"],
    extras: "",
    type: "tech",
    madeat: "MI Hackathon",
    year: 2021,
    filter: "mobile-app",
  },
];
